

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: linkedin
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3307:3306'
  mailhog:
    image: mailhog/mailhog
    ports:
      - '1025:1025' # SMTP port
      - '8025:8025' # Web UI port